### ISSUE TITLE
Keyboard shortcut for Rescan MIDI

### ISSUE THREAD

**Issue by crenz** [krevis/MIDIApps#106]
@krevis, thank you for creating MIDI Monitor! It's become a really helpful and indispensable tool for me. 

It would be great if it were possible to rescan MIDI devices via a keyboard shortcut, e.g. ⌘R. RIght now, I can only trigger that via the menu.

**Comment by krevis** [comment]
Thanks for the patch, it looks fine to me. You could also just use Audio MIDI Setup, which already has command-R to "Refresh MIDI Setup", which I believe is the same thing.

I'm curious, though, why do you need to do this so frequently? What part of your setup doesn't update automatically?

**Comment by crenz** [comment]
It's more a convenience thing – I often skip opening Audio MIDI setup and use MIDI Monitor directly to verify proper MIDI connectivity. And with some USB devices, it can be helpful to do a manual rescan.

**Comment by krevis** [comment]
Which USB devices, in particular, have you found that need this?  Just asking out of curiosity, since I don't recall using any USB-MIDI interfaces that didn't automatically update when plugged or unplugged.
