### ISSUE TITLE
Automatically created new window doesn't spy

### ISSUE THREAD

**Issue by krevis** [krevis/MIDIApps#24]
1. In Preferences > Sources, check "New windows will use these sources": "MIDI Sources" and "Spy on output to destinations".
2.  Also check "Automatically open window for new sources".
3. Add a new MIDI port -- plug  in a device, or turn on network or IAC

Expected: New window has spying turned on for the new source
Actual: Spying is not turned on for the new source.

**Comment by triplef** [comment]
I’m having the same issue, prevents debugging MIDI issues upon connection. Would be great if this could be fixed.

**Comment by krevis** [comment]
This appears to be working as expected after the rewrite for version 1.5.  Release coming up soon.
