### ISSUE TITLE
If I leave the midi monitor on over night - at some point it stops receiving notes

### ISSUE THREAD

**Issue by johndpope** [krevis/MIDIApps#42]
Yet - when I open a new window (without closing the app) - everything comes good again. 
It's an out there edge case - but I'm seeing it happen sooner in a different use case. 

I'm not on the latest code base - but do you have any idea what is the source of this? 
It's like the vvmidimanager / nodes or core midi has died - the c inboard myMIDIReadProc stops processing data. 
void myMIDIReadProc(const MIDIPacketList *pktlist, void *refCon, void *connRefCon) 

I've tried calling MIDIRestart(); to re-kick start things but it doesn't help. 
OSStatus status = MIDIRestart();

**Comment by krevis** [comment]
Is the machine going to sleep overnight? It wouldn't be surprising if USB devices disappeared and reappeared across a sleep/wake cycle, and when that happens, CoreMIDI might also be sending notifications that endpoints disappeared and reappeared. It's possible that either my code or your code is not correctly handling that.

Also, what MIDI interface are you using? I just got a report that the MOTU MIDI driver crashes the MIDIServer when the device (a MOTU FastLane 2x2) is unplugged/replugged, or the machine goes to sleep. Check the Console for any messages about the MIDIServer, or crash logs for "MIDIServer" in the "User Diagnostic Reports" section.

**Comment by johndpope** [comment]
@krevis - thanks for your efforts on this project. 
I'm doing some spring cleaning & closing out some old github tickets.
151 to go.
