### ISSUE TITLE
Old version of MIDI Monitor's driver

### ISSUE THREAD

**Issue by dandaka** [krevis/MIDIApps#47]
When I launch MIDI Monitor after its latest update (now it is 1.3.2), I see this error message:

> There is an old version of MIDI Monitor's driver installed, but it could not be removed. To fix this, remove the old driver. (It is probably "Library/Audio/MIDI Drivers/MIDI Monitor.plugin" in your home folder.)
> 
> For now, MIDI Monitor will not be able to spy on the output of other MIDI applications, but all other features will still work.

But there are no `Library/Audio/MIDI Drivers/MIDI Monitor.plugin` file :(

**Comment by krevis** [comment]
Are you sure?  In recent versions of OS X, the Finder hides the Library folder in your home folder, but it's still there.  Here's [how to see it](http://osxdaily.com/2013/10/28/show-user-library-folder-os-x-mavericks/).

If that doesn't work, does restarting your computer help?

**Comment by dandaka** [comment]
Works fine, thank you for the tip.

Actually there are two (maybe more) Library folders in OSX. I was looking into:

/Library

You are talking about

~/Library
(which is /Users/{usrname}/Library

**Comment by krevis** [comment]
That's why I said "in your home folder".  I guess I should reword the text and put that up front, or even add a button to go there directly.

It would be more clear to use "~", but most Mac users didn't learn UNIX in the 80s, don't use the shell, and thus don't know what "~" means.

**Comment by dandaka** [comment]
Since "Library" is not visible by default, it only adds to confusion. Better text would help for sure.

**Comment by krevis** [comment]
Updated this flow in version 1.4. There is now a button to show the folder in question.
