### ISSUE TITLE
Not loading sysex files (either drag and drop or +)

### ISSUE THREAD

**Issue by carltaylor43** [krevis/MIDIApps#51]
tried a few files and I cant get it to load anything. Im on OS X 10.10.5

**Comment by krevis** [comment]
I haven't heard from anyone else with this problem. Can you give more details?

- What exact file are you trying to add? Could you add it to this issue?
- What happens when you do it?

**Comment by carltaylor43** [comment]
Hi... re-downloaded the app and ran it again. Now it works without problems. The issue was that after I opened the app, I moved it to another folder. Sorry about opening an issue for this. Stupid me!

**Comment by krevis** [comment]
No worries!
