### ISSUE TITLE
MIDI Monitor auto-select new MIDI devices

### ISSUE THREAD

**Issue by DisasterAreaDesigns** [krevis/MIDIApps#65]
There is currently an option to allow MIDI Monitor to open a new window when a device is connected, but I frequently reconnect the same device during testing and it would be really nice if MM would just auto-connect and start monitoring.

Thanks!

**Comment by cSmout** [comment]
+1 For this! I Also frequently disconnect and connect the same device, would be awesome not to have to remember to select it quickly before I can grab MIDI off it

**Comment by thealienthing** [comment]
Hey guys! I just implemented this feature on my machine and I’ll make a pull request once I have checked for potential bugs. 

Thanks for calling attention to this! This is the perfect feature for a little baby dev like me to add as my first contribution to an open source project.

**Comment by myklemykle** [comment]
Brill!  MM is great, but I have to restart it whenever I reboot my under-development Bluetooth MIDI device.  At the moment, I need to do that about once every five minutes. Not having to do that would be sooooooo relaxing .... =)

**Comment by krevis** [comment]
This has finally been released in version 1.4.1.  Sorry for the ridiculous delay.
