### ISSUE TITLE
MIDI Monitor Broken in MacOS Big Sur

### ISSUE THREAD

**Issue by vjmuzik** [krevis/MIDIApps#77]
This error message pops up when opening the application, MIDI Destinations then disappears as expected after receiving this error. I did reinstall and it didn't make a difference, however even once past the error message no MIDI Sources are receiving any data.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/5726966/91098335-4729e200-e62f-11ea-8d33-ff91f37eb673.png">

**Comment by krevis** [comment]
Thanks for letting me know.  Not sure what's going wrong, probably some new security thing, but I'll have to fix it.

I should give up on trying to have the app install its MIDI driver when it starts up, and instead just provide an installer package. That would require a restart, but the whole process might be more reliable.

**Comment by krevis** [comment]
Which version of Big Sur were you using?

As of Big Sur beta 6 and 7, I'm not seeing this alert.

What I *am* seeing is that the "spy on output to destinations" feature doesn't work.  That looks like a bug on Apple's side. I filed an issue in Feedback Assistant: FB8712999.

**Comment by krevis** [comment]
Never mind; I can repro the original problem now on Big Sur 11.0.1 Beta (20B5012d).  Fixed in commit 48dec8de.

("Spy on output to destinations" still doesn't work, and that's still Apple's bug.)

**Comment by krevis** [comment]
This should now be fixed in version 1.4.1.

**Comment by gmarinov** [comment]
to add to this, for anyone who's trying to get spying to work on an older version of macOS:

- MIDI Monitor may install its driver into the user library folder, i.e. ~/Library/Audio/MIDI Plugins, while other drivers are available in e.g. /Library/Audio/...
- in addition, the driver may remain quarantined. the quarantine flag may be removed using `xattr -d -r ...`
- moving the non-quarantined driver into the common midi drivers folder appears to fix things _after a restart_.(/Library/Audio/... for older macOS, e.g. Mojave etc; and ~/Library/Audio/... on newer macOS)
