### ISSUE TITLE
Some message cell backgrounds don't match system theme in MIDI Monitor when using dark mode on Big Sur

### ISSUE THREAD

**Issue by kisielk** [krevis/MIDIApps#82]
In Big Sur, when using dark mode, the messages list looks like this:

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/58618/102815571-65a3ae00-4381-11eb-82a2-768f5bccf89b.png">

Some cells have backgrounds that don't match the system theme.

**Comment by krevis** [comment]
Thanks for noticing that.  Somehow it was never a problem before Big Sur.
Fix will be in the next release (fixed in commit 4c9e0e29).
